#!/bin/bash

# Usage:
#  - Run all the tests: scripts/test
#  - Filter by pattern: scripts/test "test name"
# export NO_COLOR=true

if [ $# -eq 0 ]; then
    deno test --allow-read --allow-write --unstable src/test/**
else
    deno test --allow-read --allow-write --unstable --filter "$1" src/test/**
fi

