name: Flat

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    # Daily 5am
    - cron: '0 5 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # The Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.thingspeak.com/channels/581842/feed.json?days=2
          downloaded_filename: last-2-days.json