name: Process Lake Almanac for yesterday

on:
    # push:
    #   branches:
    #     - main
    workflow_dispatch:
    schedule:
        # Daily 5am
        - cron: '0 5 * * *'

jobs:
    scheduled:
        runs-on: ubuntu-latest
        steps:
            # Check out the repository so it can read the files inside of it and do other operations
            - name: Check out repo
              uses: actions/checkout@v2
            # This step installs Deno, which is a new Javascript runtime that improves on Node. We'll use it for postprocessing later
            - name: Setup deno
              uses: denoland/setup-deno@main
              with:
                  deno-version: v1.x
            - name: Fetch data
              uses: githubocto/flat@v3
              with:
                  # This is an unused http_url (as postprocess makes all the requests it needs) but is currently required to exist by the action
                  http_url: https://cdn.skypack.dev/dayjs@1.10.6
                  downloaded_filename: skypack-dayjs.txt
                  postprocess: src/archiver.ts
