name: Test runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: scripts/test